---
# Ensure that all cloud-init services are enabled.  We need
# cloud-config enabled, and we may as well enable the others while
# we're at it.
- name: Enable all cloud-init services
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  tasks:
    - name: Enable all cloud-init services
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
      loop:
        - cloud-init-local
        - cloud-init
        - cloud-config
        - cloud-final
