---
- name: Import AWS playbook
  ansible.builtin.import_playbook: aws.yml

- name: Import base image playbook
  ansible.builtin.import_playbook: base.yml

# TODO: Remove this when and if that becomes possible.  See
# cisagov/skeleton-packer#301.
- name: >-
    Import playbook to install prerequisites for the Netplan
    configuration fix
  ansible.builtin.import_playbook: install-prerequisites-for-netplan-configuration-fix.yml

- name: Import cloud-init playbook
  ansible.builtin.import_playbook: cloud_init.yml

- name: Import UFW playbook
  ansible.builtin.import_playbook: ufw.yml

# The AWS playbook must run before this one, since this playbook uses
# a user group created in the AWS playbook.
- name: Import VNC playbook
  ansible.builtin.import_playbook: vnc.yml

# The VNC playbook must run before this one, since this playbook uses
# a user created in the VNC playbook.
- name: Import Terraform playbook
  ansible.builtin.import_playbook: terraform.yml

# The VNC playbook must run before this one, since this playbook uses
# a user created in the VNC playbook.
- name: Import Xfce playbook
  ansible.builtin.import_playbook: xfce.yml
