---
- name: Import base image playbook
  ansible.builtin.import_playbook: base.yml

- name: Import UFW playbook
  ansible.builtin.import_playbook: ufw.yml

- name: Import VNC playbook
  ansible.builtin.import_playbook: vnc.yml

- name: Import cloud-init playbook
  ansible.builtin.import_playbook: cloud_init.yml

- name: Import AWS playbook
  ansible.builtin.import_playbook: aws.yml
