---
collections:
  - community.general
roles:
  - name: amazon_efs_utils
    src: https://github.com/cisagov/ansible-role-amazon-efs-utils
  - name: amazon_ssm_agent
    src: https://github.com/cisagov/ansible-role-amazon-ssm-agent
  - name: assessment_tool
    src: https://github.com/cisagov/ansible-role-assessment-tool
  - name: automated_security_updates
    src: https://github.com/cisagov/ansible-role-automated-security-updates
  - name: banner
    src: https://github.com/cisagov/ansible-role-banner
  - name: chrony_aws
    src: https://github.com/cisagov/ansible-role-chrony-aws
  - name: clamav
    src: https://github.com/cisagov/ansible-role-clamav
  - name: cloudwatch_agent
    src: https://github.com/cisagov/ansible-role-cloudwatch-agent
  - name: htop
    src: https://github.com/cisagov/ansible-role-htop
  - name: nvme
    src: https://github.com/cisagov/ansible-role-nvme
  - name: persist_journald
    src: https://github.com/cisagov/ansible-role-persist-journald
  - name: pip
    src: https://github.com/cisagov/ansible-role-pip
  - name: python
    src: https://github.com/cisagov/ansible-role-python
  - name: remove_python2
    src: https://github.com/cisagov/ansible-role-remove-python2
  - name: terraform
    src: https://github.com/cisagov/ansible-role-terraform
  - name: ufw
    src: https://github.com/cisagov/ansible-role-ufw
  - name: upgrade
    src: https://github.com/cisagov/ansible-role-upgrade
  - name: vnc
    src: https://github.com/cisagov/ansible-role-vnc-server
  - name: xfce_cool
    src: https://github.com/cisagov/ansible-role-xfce-cool
