---
- hosts: all
  name: Install Terraform and terraform-docs
  become: yes
  become_method: sudo
  roles:
    - role: terraform
      vars:
        # According to the RTA folks they are on 0.14.  This is the
        # most recent 0.14 version.
        terraform_version: 0.14.11
