---
- hosts: all
  name: Install Terraform, Ansible, and related tools
  become: yes
  become_method: sudo
  roles:
    - role: terraform
      vars:
        # According to the RTA folks they are on the most recent
        # version of Terraform.
        terraform_version: 1.0.11
    - role: assessment_tool
      vars:
        group: "{{ vnc_user }}"
        install_dir: /home/{{ vnc_user }}/
        owner: "{{ vnc_user }}"
        pip_packages:
          - ansible
          - boto3
  tasks:
    - name: Install git and the AWS CLI tool
      ansible.builtin.package:
        name:
          - awscli
          - git
  vars:
    # The username for the VNC user
    vnc_user: "{{ lookup('aws_ssm', '/vnc/username') }}"
