---
- hosts: all
  name: Install Terraform, Ansible, and related tools
  become: yes
  become_method: sudo
  tasks:
    - name: Install Terraform
      ansible.builtin.include_role:
        name: terraform
      vars:
        # According to the RTA folks they are on the most recent
        # version of Terraform.
        terraform_terraform_version: 1.0.11
    - name: Set up Python virtualenv with Ansible and Boto3
      ansible.builtin.include_role:
        name: assessment_tool
      vars:
        assessment_tool_group: "{{ vnc_user }}"
        assessment_tool_install_dir: /home/{{ vnc_user }}/
        assessment_tool_owner: "{{ vnc_user }}"
        assessment_tool_pip_packages:
          - ansible
          - boto3
    - name: Install the AWS CLI tool and git
      ansible.builtin.package:
        name:
          - awscli
          - git
  vars:
    # The username for the VNC user
    vnc_user: "{{ lookup('aws_ssm', '/vnc/username') }}"
